language: php

php:
  - 7.1

cache:
  directories:
    - builder
    - $HOME/.composer/cache

install:
  - git clone https://github.com/rob006-software/flarum-translations-builder.git builder || git -C builder pull
  - composer install --working-dir builder

script: builder/yii translations/update '' "@app/../config.php" --update=0

after_success: git diff
